steps:
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'blog'
    - 'gs://${_GCS_BUCKET}/blog'
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'setmeta'
    - '-r'
    - '-h'
    - 'cache-control: max-age=86400'
    - 'gs://${_GCS_BUCKET}/*'

